require --no-auth in MSYS2

diff --git a/runx b/runx
--- a/runx
+++ b/runx
@@ -1,7 +1,7 @@
 #! /bin/bash
 # runx: Provide an X server in Cygwin, MSYS2 or WSL.
 
-Version="v0.2.7"
+Version="v0.2.8"
 
 usage() {                       # Usage information (--help)
   echo "runx - Run Linux GUI applications on MS Windows.
@@ -91,7 +91,7 @@ finish() {                      # Clean up and terminate
       }
       [ "$Xserverwinpid" ] && tasklist.exe /FI "PID eq $Xserverwinpid" | grep -q "$Xserverwinpid" && {
         verbose "Terminating X server $Xserver :$Newdisplaynumber. Windows PID: $Xserverwinpid"
-        taskkill.exe /F /PID $Xserverwinpid 2>&1
+        taskkill.exe /F /PID $Xserverwinpid
       }
       exit "${1:-0}"
     ;;
@@ -294,12 +294,6 @@ check_host() {                  # Check host environment
   [ "$Hostip" ] || Hostip="$(ipconfig.exe | rmcr | grep 'IPv4' | head -n1 | rev | cut -d' ' -f1 | rev)"
   verbose "Host IP adress: $Hostip"
   
-  [ "$Xauthentication" = "yes" ] && [ "$Winsubsystem" = "MSYS2" ] && {
-    note "MSYS2 does not provide xauth to create a cookie.
-  Fallback: Enabling discouraged option --no-auth."
-    Xauthentication="no"
-  }
-  
   return 0
 }
 
@@ -329,13 +323,19 @@ check_dependencies() {          # Check all dependencies
   
   # xauth
   [ "$Xauthentication" = "yes" ] && {
-    check_dependency xauth || error "Missing dependency: xauth
+    check_dependency xauth || {
+      case $Winsubsystem in
+        WSL|CYGWIN) error "Missing dependency: xauth
   Cannot create an authorization cookie for X server access.
-  Please install package in $Winsubsystem:  xauth
-  You can disable cookie authentication with discouraged option --no-auth."
+  Please install package 'xauth'.
+  You can disable cookie authentication with discouraged option --no-auth." ;;
+        MSYS2) error "Missing dependency: xauth
+  Cannot create an authorization cookie for X server access.
+  MSYS2 does not provide xauth. Rather use Cygwin or WSL instead.
+  You can disable cookie authentication with discouraged option --no-auth." ;;
+      esac
+    }
   }
-  
-  # mcookie ### FIXME
   
   # X server VcXsrv or XWin
   Vcxsrvexe="$(command -v vcxsrv.exe)"
@@ -589,8 +589,10 @@ main() {
       unset XAUTHORITY
       verbose "DISPLAY=$DISPLAY"
       warning "Option --no-auth: Cookie authentication is disabled!
-  Your X server $Xserver listens on TCP connections without any protection!
-  This is a security leak. Please use option --no-auth for debugging only."
+      SECURITY RISC!
+  Your X server $Xserver listens on TCP connections without any protection.
+  Others could try to access your system through network connections. 
+  Please use option --no-auth for debugging only."
       echo "DISPLAY=$DISPLAY"
     ;;
   esac
